apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dzbojwtr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dzbojwtr:890c388d3d55735db5339daf9a9d647463883292@sha256:e78d6212a97bbb8d9ad596efcd051847214ad9f6e62de1bfb302d13fbcea7b03
          name: container-image
